# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# IMPORTANT: You must stop your jekyll build --watch command, and re-run after any changes are made here,
# in order for changes to this file to go into effect
#
title: Digital Security Exchange
email: ops@digitalsecurityexchange.org
description: >- # this means to ignore newlines until "baseurl:"
  Digital Security Exchange.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Server Config options
livereload: false     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

footernav:
- { title: 'About', href: '/about' }
- { title: 'How We Help', href: '#howWeHelp' }
- { title: 'Providers', href: '#providers' }
- { title: 'News', href: '/updates' }
- { title: 'Support the DSX', href: '/support' }

mainnav:
- { title: 'About', href: '/about' }
- { title: 'How We Help', href: '#howWeHelp' }
- { title: 'Providers', href: '#providers' }
- { title: 'News', href: '/updates' }

finenav:
- { title: 'Privacy', href: '/privacy' }
- { title: 'Security', href: '/security' }
- { title: 'Terms', href: '/terms' }
- { title: 'Conduct', href: '/code' }

howWeHelpCardData:
- { number: '1', title: 'Store information safely', content: 'Get help learning which apps are best for storing donor lists and collaborating on important documents.', image: 'store-info-securely.svg' }
- { number: '2', title: 'Secure your communications', content: 'Ensure that communication between your team, volunteers and citizens are private and your response protocols are secured.', image: 'secure-communications.svg' }
- { number: '3', title: 'Protect private information', content: 'Keep private matters within your team. Learn best practices for protecting accounts and identities.', image: 'protect-private-info.svg' }

providerCardData:
- { number: '1', name: 'Guardian Project', image: 'guardian-logo.png', url: 'https://guardianproject.info'}
- { number: '2', name: 'Access Now', image: 'access-logo.png', url: 'https://www.accessnow.org' }
- { number: '3', name: 'Freedom of the Press', image: 'freedom-logo.png', url: 'https://freedom.press' }
- { number: '4', name: 'Security+', image: 'security-plus-logo.png', url: 'https://www.securitypositive.com' }
- { number: '5', name: 'Constitutional Communications', image: 'constitutional-logo.png', url: 'https://constitutionalcommunications.org' }
- { number: '6', name: 'EFF', image: 'eff-logo.png', url: 'https://www.eff.org' }
- { number: '7', name: 'Security First', image: 'security-first-logo.png', url: 'https://secfirst.org' }
- { number: '8', name: 'eQualitie', image: 'equalitie-logo.png', url: 'https://equalit.ie' }

tagLine:
  line1: 'Keeping U.S. civil society'
  line2: 'safe from digital attack'


sass:
  sass_dir: css
  style: compressed

keep_files: ['forms']

# Exclude from processing.
# The following items will not be processed
exclude:
- README.md
- LICENSE.md
- submissions
- version.py
- Makefile
- Gemfile
- Gemfile.lock
- THEME_README.md
- Vagrantfile
- bootstrap.sh
- release-to-github.sh
