<?php
include "config.php";
include "functions.php";

$fields = array(
  'name',
  'title',
  'organization',
  'website',
  'affiliates',
  'trainerCheck',
  'softwareExperCheck',
  'facilitatorCheck',
  'otherCheck',
  'otherText',
  'hardwareExpertCheck',
  'antiCorruptionCheck',
  'antiWarCheck',
  'cultureCheck',
  'domesticViolenceCheck',
  'educationCheck',
  'economicChangeCheck',
  'environmentCheck',
  'electionMonitoringCheck',
  'freedomToolCheck',
  'freedomExpressionCheck',
  'fundingCheck',
  'healthIssuesCheck',
  'humanRightsCheck',
  'internetTelecomsCheck',
  'LGBTCheck',
  'policyCheck',
  'politicsCheck',
  'privacyCheck',
  'rapidResponseCheck',
  'refugeesCheck',
  'reproductiveCheck',
  'infoSecurityCheck',
  'womensRightsCheck',
  'youthRightsCheck',
  'incidentAnalysisCheck',
  'threatModelingCheck',
  'bestPracticeCheck',
  'trainingCheck',
  'policyWritingCheck',
  'securingHardwareCheck',
  'securingInfrastructureCheck',
  'securingDataCheck',
  'securingCommunicationsCheck',
  'secureCollaborationCheck',
  'securityTravelCheck',
  'protestSecurityCheck',
  'socialEngineeringCheck',
  'safeReportingCheck',
  'hackRespondingCheck',
  'onlinePrivacyCheck',
  'malwareAttackCheck',
  'doxxedTrolledCheck',
  'circumventionCheck',
  'androidDevCheck',
  'iosDevCheck',
  'webDevCheck',
  'phone',
  'email',
  'signal',
  'pgp',
  'serviceHandle',
  'service',
  'qualifications',
);

session_start();

process_form('provider', $fields, $path_to_submissions, $gnupg_key_fp);

?>
